### ISSUE TITLE
能一起合作吗

### ISSUE THREAD

**Issue by 17702513221** [gengyanlei/fire-detect-yolov4#1]
我最近也在做yolov4的火焰检测，能加QQ好友吗，接下来准备做yolov4剪枝和tensorrt部署。QQ：406174050
我因为工作可以去工厂采集数据，后面也方便建立数据集

**Comment by gengyanlei** [comment]
@17702513221 可以。

**Comment by gengyanlei** [comment]
@17702513221 我再次更新了数据集，增加了数据。
