### ISSUE TITLE
OSError: libopencv_core.so.2.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lws6885** [gengyanlei/fire-detect-yolov4#11]
当我调用latest_darknet_API.py进行推理时，报如下错误：OSError: libopencv_core.so.2.4: cannot open shared object file: No such file or directory.请问怎么解决

**Comment by gengyanlei** [comment]
@lws6885 
apt-get install libopencv-dev 安装即可

**Comment by April4lu** [comment]
执行apt-get install libopencv-dev之后安装的是最新版本，并提示”libopencv-dev is already the newest version (3.2.0+dfsg-4ubuntu0.1).“

所以还是报错OSError: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
