### ISSUE TITLE
Yolov4模型只能检测火焰，不能检测烟雾

### ISSUE THREAD

**Issue by gugumituo** [gengyanlei/fire-detect-yolov4#12]
fire.names里面只有火焰，经测试只能识别火焰，不能识别烟雾，请问用Yolov4算法如何识别烟雾？

**Comment by gengyanlei** [comment]
@gugumituo 
请看readme
https://github.com/gengyanlei/fire-detect-yolov4/blob/master/README_ZN.md

**Comment by gugumituo** [comment]
好的，谢谢！
