### ISSUE TITLE
OSError: libopencv_core.so.2.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by April4lu** [gengyanlei/fire-detect-yolov4#13]
执行 apt-get install libopencv-dev之后安装了最新版本，提示”libopencv-dev is already the newest version (3.2.0+dfsg-4ubuntu0.1).“

但该问题任然存在

**Comment by gengyanlei** [comment]
@April4lu 
我用的docker容器，没有遇到你这个问题，应该是版本的问题，可以切换，又或者是你采用make安装的opencv

**Comment by April4lu** [comment]
感谢作者~

**Comment by zaiquanyang** [comment]
> 感谢作者~
请问你解决了吗？怎么解决的呀

**Comment by zaiquanyang** [comment]
> 感谢作者~

请问你是怎么解决的呀

**Comment by April4lu** [comment]
> > 感谢作者~
> 
> 请问你是怎么解决的呀

我后面就没有解决了，猜想卸载再安装，安装的时候指定版本试试看

**Comment by gengyanlei** [comment]
@April4lu 我是在docker容器内 直接apt-get安装的libopencv==2.4
