### ISSUE TITLE
yolov4 模型转换成onnx模型后,inference结果差距较大

### ISSUE THREAD

**Issue by dubaicv** [gengyanlei/fire-detect-yolov4#14]
这是两者的inference 输出 :
darknet box: [0.44398072, 0.25001103, 0.10880162 ,0.27873766]  conf : 0.6275723
onnx  box: [0.3904399 ,0.10827315 ,0.49689564 ,0.39131567]       conf: 0.67223823

这是我用的测试的图片：
https://image.baidu.com/search/detail?ct=503316480&z=undefined&tn=baiduimagedetail&ipn=d&word=%E6%89%93%E7%81%AB%E6%9C%BA&step_word=&ie=utf-8&in=&cl=2&lm=-1&st=undefined&hd=undefined&latest=undefined&copyright=undefined&cs=2444222964,2620753514&os=2385169486,2135497603&simid=3447159448,455013216&pn=2&rn=1&di=91520&ln=1681&fr=&fmq=1609410555919_R&fm=&ic=undefined&s=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&is=0,0&istype=0&ist=&jit=&bdtype=0&spn=0&pi=0&gsm=0&objurl=https%3A%2F%2Fgimg2.baidu.com%2Fimage_search%2Fsrc%3Dhttp%253A%252F%252Fimg.alicdn.com%252Fbao%252Fuploaded%252Fi4%252F2682881798%252FTB2ef_WfmtYBeNjSspaXXaOOFXa_%2521%25212682881798.jpg_300x300.jpg%26refer%3Dhttp%253A%252F%252Fimg.alicdn.com%26app%3D2002%26size%3Df9999%2C10000%26q%3Da80%26n%3D0%26g%3D0n%26fmt%3Djpeg%3Fsec%3D1612002549%26t%3Ddee2278454e7ce26bfb4b948c703392d&rpstart=0&rpnum=0&adpicid=0&force=undefined

@gengyanlei   请问下是什么原因呢？谢谢

**Comment by gengyanlei** [comment]
@dubaicv 
你是用我上传的onnx转的模型么
