### ISSUE TITLE
darknet_API.py在最新版下无法运行

### ISSUE THREAD

**Issue by helloyan** [gengyanlei/fire-detect-yolov4#2]
array_to_image函数不存在

**Comment by gengyanlei** [comment]
这个函数是在darknet文件夹下面

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/90997836-32c8f380-e5f5-11ea-8cc4-9029f187ca0d.png)

**Comment by gengyanlei** [comment]
@helloyan 我上传了适合自己代码的对应darknet版本。没有及时更新darknet的代码，凑合着看看。
