### ISSUE TITLE
Colab Demo?

### ISSUE THREAD

**Issue by Adeel-Intizar** [gengyanlei/fire-detect-yolov4#22]
Hello, Thank you for your great work
Can you provide a Colab Notebook Demo for this amazing repo, It will help everyone and it will be much appreciated,
thank you

**Comment by gengyanlei** [comment]
@Adeel-Intizar 
https://github.com/gengyanlei/fire-detect-yolov4/blob/master/yolov5/best.pt
Here is the weight file of yolov5 for smoke-fire detection. You can run it directly.

**Comment by Adeel-Intizar** [comment]
@gengyanlei by default how many classes does yolov5 detect? and is there any explanation or documentation of this repo?

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/111556733-24773a80-87c6-11eb-89ab-ecf63791ecb4.png)

**Comment by gengyanlei** [comment]
Please refer to the readme.
