### ISSUE TITLE
Weights file?

### ISSUE THREAD

**Issue by reddevil1310** [gengyanlei/fire-detect-yolov4#26]
Can you share weights file to detect smoke and fire. 
Thank you!

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/117779381-367ad400-b271-11eb-8000-0628cd0ed460.png)

**Comment by reddevil1310** [comment]
Sorry but I can download yolov4 fire-detect's weights from BaiDu. Can you upload to Google Drive?

**Comment by gengyanlei** [comment]
you can use yolov5's weight, it support fire and smoke.

**Comment by reddevil1310** [comment]
Thank you very much!

**Comment by cong235** [comment]
> @reddevil1310
> you can use yolov5's weight, it support fire and smoke. yolov4 only support fire.

Can you share yolov4 version google drive link?
I cant download from baidu man
