### ISSUE TITLE
"yolov4 fire-detect's weight-BaiDuYunPanDownLoadLink"  Not working 

### ISSUE THREAD

**Issue by Maheshiitmandi** [gengyanlei/fire-detect-yolov4#27]
Unable to download the yolov4 weights because this link is not opening.

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/119448067-6642d500-bd63-11eb-95b4-173b3a0d55b5.png)

@Maheshiitmandi 链接有效

**Comment by Maheshiitmandi** [comment]
Thanks @gengyanlei for replying. I tried to access with different devices but unable to open any Baidu link. But I am able to access google drive link. May be location issue. Please can you help to download yolov4 fire weights.

**Comment by gengyanlei** [comment]
@Maheshiitmandi 
you can use yolov5s's weight file, it's better than yolov4's weight file

**Comment by Maheshiitmandi** [comment]
I used yolov5 weights on yolov5 model which works fine. But I need yolov4 weights because I wanted to use these yolov4 weights with nvidia deepstream which supports up to yolov4(as per my knowledge). So can I use yolov5 weights on yolov4 architecture?(just for confirmation).
