### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by PiPiNam** [gengyanlei/fire-detect-yolov4#28]
下载了您提供的 “烟火(2059张图像,含标签)” 后发现里面只有含有火焰的标签，并未发现烟雾的标签。

我想使用您的YOLO v5 实现一个能同时检测烟雾和火焰的检测器，请问您用来训练v5的数据集烟雾火焰数据集可以开源吗？谢谢！

**Comment by gengyanlei** [comment]
@PiPiNam 
你可以自己在开源的无标签数据集上自己标注；每个人的标注规则不一样，因此只开源火的标签，不会开源烟雾的！
