### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by sunmouren** [gengyanlei/fire-detect-yolov4#29]
你好呀，我通过你的下载链接下载数据集后，里面的文件只有火焰的图片，请问哪个链接是和你用yolov5训练的火焰+烟雾的数据呢？

**Comment by gengyanlei** [comment]
@sunmouren 请看readme！里面都有说明，不要只下载数据，然后再问别人，readme的作用就是解释的，详细看一下哈。

**Comment by sunmouren** [comment]
我知道那readme，就是因为我下载你分享的烟火数据集百度云后，看了只有火焰的才过来问一下的。
