### ISSUE TITLE
烟雾能检测么？

### ISSUE THREAD

**Issue by JJXXV** [gengyanlei/fire-detect-yolov4#5]
实际预训练的模型，能否检测烟雾呢？因为我看到demo图片有一张是有烟雾检测的分类的。

**Comment by gengyanlei** [comment]
@JJXXV 我开源的数据集包含烟雾图像，但是标注只有1类；开源模型只有fire类，你可以自己再图像上标注烟雾类别，即可。

**Comment by JJXXV** [comment]
OK,谢啦
