### ISSUE TITLE
Cannot access Baidu pan from Germany

### ISSUE THREAD

**Issue by nanthamjeeva** [gengyanlei/fire-detect-yolov4#6]
I cannot access the fire-yolov4-weights and fire-dataset from the cloud Baidu...  Could you please upload them on google drive or similar ? Thanks

**Comment by gengyanlei** [comment]
@nanthamjeeva 
![image](https://user-images.githubusercontent.com/22360785/94326747-c4eb5f80-ffd8-11ea-85a7-16424127828f.png)

**Comment by gengyanlei** [comment]
Hello, I don’t have a Google Cloud Disk account. The Google link containing 2059 fire images was stored for help.

**Comment by nanthamjeeva** [comment]
> Hello, I don’t have a Google Cloud Disk account. The Google link containing 2059 fire images was stored for help.
Could you try and upload it to mega.nz or similar in a way I can use it ? It would really help if I train my model with the dataset you have . Or I can train your model with my data....  

Please try , 

Thanks in advance

**Comment by nanthamjeeva** [comment]
> @nanthamjeeva
> ![image](https://user-images.githubusercontent.com/22360785/94326747-c4eb5f80-ffd8-11ea-85a7-16424127828f.png)

Also the Google links are blocked and I need permission ...

**Comment by gengyanlei** [comment]
Sorry, I currently have no way to implement a Google Cloud Disk account.

**Comment by gengyanlei** [comment]
@nanthamjeeva 
Hello, I have open sourced yolov5-fire-smoke-detect-weight, you can try.

**Comment by gengyanlei** [comment]
@nanthamjeeva 
I add new google drive download link，you can try download it。

**Comment by nanthamjeeva** [comment]
Thank you so much 🥇
