### ISSUE TITLE
run crash

### ISSUE THREAD

**Issue by zj376879088** [gengyanlei/fire-detect-yolov4#7]
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.05
nms_kind: greedynms (1), beta = 0.600000 
Total BFLOPS 127.232 
avg_outputs = 1046213 
 Allocate additional workspace_size = 52.43 MB 
 Try to load weights: ./backup_fire/yolov4-fire_best.weights 
Loading weights from ./backup_fire/yolov4-fire_best.weights...
 seen 64, trained: 128 K-images (2 Kilo-batches_64) 
Done! Loaded 162 layers from weights-file 
Loaded - names_list: ./cfg/fire.names, classes = 1 
Segmentation fault (core dumped)
只要调用predict_image就会崩溃，而且没有任何有效信息。

**Comment by gengyanlei** [comment]
@zj376879088 
由于官方yolov4-darknet代码更新了，因此本文的训练代码只适合本人版本的代码，建议重写根据官方代码写图像预测！

**Comment by gengyanlei** [comment]
@zj376879088 
你试试我新上传的文件，我把自己编译好的darknet-yolov4代码上传了，darknet_api.py和这个是配套的。

**Comment by zj376879088** [comment]
lib = CDLL("./libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
调用编译你编译好的so，抛出上面错误，应该是你用cuda10关联编译的，我的目前使用的是cuda9.0，无法直接使用哦！

**Comment by gengyanlei** [comment]
@zj376879088 
哦，我忘记说明这个了。我用的docker-cuda10，你可以创建1个docker，这样可以使用不同的cuda版本。

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/99234814-fee61e80-282f-11eb-945a-3f2e36f20ec3.png)

**Comment by gengyanlei** [comment]
@zj376879088 
你可以基于我的文件重新编译一下，但是官方要求cuda10.0以上。如果你要用cuda10.2，也可以在我提供的文件上重新编译。即可
